name: 'Tauri Signature to Kubernetes Secret'
description: 'Extract Tauri build signatures and store them in Kubernetes secrets'
author: 'YourName'
branding:
  icon: 'lock'
  color: 'blue'

inputs:
  tauri-bundle-path:
    description: 'Path to Tauri bundle directory'
    required: true
    default: 'src-tauri/target/release/bundle'
  
  kubernetes-config:
    description: 'Complete kubeconfig content (YAML format)'
    required: true
  
  kubernetes-namespace:
    description: 'Kubernetes namespace for the secret'
    required: false
    default: 'default'
  
  secret-name:
    description: 'Name of the Kubernetes secret'
    required: true
  
  secret-key-prefix:
    description: 'Prefix for secret keys'
    required: false
    default: 'tauri-sig'
  
  platforms:
    description: 'Comma-separated list of platforms to process (windows,macos,linux)'
    required: false
    default: 'windows,macos,linux'
  
  github-token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}

outputs:
  signatures-found:
    description: 'Number of signature files found'
  secret-updated:
    description: 'Whether the Kubernetes secret was updated'
  signature-hashes:
    description: 'JSON object containing signature hashes by platform'

runs:
  using: 'node20'
  main: 'dist/index.js'