name: 'Tauri Signature to Kubernetes Secret'
description: 'Extract Tauri build signatures and store them in Kubernetes secrets'
author: 'Punit Kashyup'

inputs:
  tauri-bundle-path:
    description: 'Path to Tauri bundle directory'
    required: true
    default: 'src-tauri/target/release/bundle'
  
  kubernetes-config:
    description: 'Complete kubeconfig content (YAML format)'
    required: true
  
  kubernetes-namespace:
    description: 'Kubernetes namespace for the secret'
    required: false
    default: 'default'
  
  secret-name:
    description: 'Name of the Kubernetes secret'
    required: true
  
  secret-key-prefix:
    description: 'Prefix for secret keys'
    required: false
    default: 'tauri-sig'
  
  platforms:
    description: 'Comma-separated list of platforms to process'
    required: false
    default: 'windows,macos,linux'

runs:
  using: 'node20'
  main: 'dist/index.js'